#url: https://y7kim.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
title: Lucas Galdino
email: lucas@lucasgaldino.com
description: "Lucas Galdino - Brazilian-Canadian medical translator and nursing student in Alicante. Specialized translation services combining language expertise with health sciences knowledge."


# Team names, titles and social links
people:
- name: Lucas Galdino
  pic: luc
  position: #
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/lucasgaldinohc/
    - title: paperclip
      url: pdf/main.pdf

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Postal address (add as many lines as necessary)
address:
  - line: Alicante, ES

# Build settings
markdown: kramdown
permalink: pretty
